### ISSUE TITLE
propTypes and other static methods

### ISSUE THREAD

**Issue by matthewmueller** [anvaka/maco#1]
This library looks sweet, very D3-like. Haven't looked too closely at it, but does it handle statics like `counter.propTypes`?

**Comment by anvaka** [comment]
Sorry for delay! This question escaped me for a while. 

`propTypes` and other static methods are absolutely possible:

``` js
var React = require('react');
var Greet = require('maco')(greeter, React);

Greet.propTypes = { name: React.PropTypes.string };
Greet.defaultProps = { name: 'Stranger' };

module.exports = Greet;

function greeter(x) {
  x.render = () =>  <div>Hello {x.props.name}!</div>;
}
```

PS: I wish you Happy New Year and lots if inspiration in 2016. I'm writing this on Dec 31, 2015.
